### ISSUE TITLE
Execution could not continue.  Script error.

### ISSUE THREAD

**Issue by chucklemaster** [TerminusEst13/Folded1000Times#28]
OS: Windows 7 (NT 6.1) Build 7601
    Service Pack 1
M_LoadDefaults: Load system defaults.
Gameinfo scan took 17 ms
W_Init: Init WADfiles.
 adding C:/Program Files (x86)/Zandronum/zandronum.pk3, 696 lumps
 adding C:/Program Files (x86)/Zandronum/doom2.wad, 2919 lumps
 adding C:/Program Files (x86)/Zandronum/announcer/ZanACG.pk3, 104 lumps
 adding C:/Program Files (x86)/Zandronum/announcer/ZanGeneric.pk3, 105 lumps
 adding C:/Users/zer0n/Desktop/gayms/Folded1000Times-master/te13-DemonSteele.pk3, 6082 lumps
I_Init: Setting up machine state.
CPU Speed: 3051 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM)2 Duo CPU E8435 @ 3.06GHz
  Family 6, Model 23, Stepping 10
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1
I_InitSound: Initializing FMOD
FMOD Sound System, copyright © Firelight Technologies Pty, Ltd., 1994-2009.
Loaded FMOD version 4.24.16
V_Init: allocate screen.
Using in-memory database. The database will not be saved on exit.
S_Init: Setting up sound.
ST_Init: Init startup screen.
P_Init: Checking cmd-line parameters...
G_ParseMapInfo: Load map definitions.
S_InitData: Load sound definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
Tried to register class 'InvisibilitySphere' more than once.
Tried to register class 'MaxArmorBonus' more than once.
Tried to register class 'MaxHealthBonus' more than once.
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 687:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 688:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 689:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 690:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 691:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 692:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 693:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 694:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 695:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 696:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 697:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 698:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 699:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 700:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 701:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 702:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 703:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 704:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 705:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 706:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 707:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 708:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 709:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 710:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 711:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 712:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 713:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 714:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 715:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 716:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 717:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 718:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 719:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 720:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 721:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 722:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 723:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 724:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 725:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 726:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 795:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 796:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 797:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 798:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 799:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 800:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 801:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 802:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 803:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 804:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 805:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 806:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 807:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 808:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 809:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 810:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 811:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 812:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 813:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 814:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 815:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 816:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 817:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 818:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 819:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 820:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 821:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 822:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 823:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 824:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 825:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 826:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 827:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 828:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 829:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 830:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 831:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 832:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 833:
Unknown identifier 'CMF_ABSOLUTEPITCH'
Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 834:
Unknown identifier 'CMF_ABSOLUTEPITCH'

Execution could not continue.

Script error, "te13-DemonSteele.pk3:decorate/sshweapons/0-cannon.dec" line 954:
Invalid state parameter a_setscale

**Comment by TerminusEst13** [comment]
This is simply a matter of a couple things not being compatible with Zandronum 2.1.2. They'll be fixed up before release, since compatibility is kind of a Big Deal here.
In the meantime, Zandronum 3.0 or G/ZDoom will run it fine.

**Comment by chucklemaster** [comment]
got it. thanks!
